### ISSUE TITLE
fitting a subset of parameters

### ISSUE THREAD

**Issue by dikshagup** [lindermanlab/ssm#124]
Hi! 

What would be the easiest way to fit reduced forms of dynamics/observation models to the data? I'd like to fix some parameters and not have them be fit.
Thank you for developing and maintaining such an awesome code base!

**Comment by slinderman** [comment]
Hi, 

Great question! There are a few ways, but they involve a little modification since we don't have an option like that exposed via the `fit` function.  If you only want to fit the observation parameters holding the transitions fixed, e.g., you can comment out the appropriate `m_step` calls in [`hmm._fit_em`](https://github.com/lindermanlab/ssm/blob/master/ssm/hmm.py#L449-L451). 

It's a bit trickier if you want to fit only some of the observation parameters, e.g. the `GaussianObservations` means while holding the covariances fixed.  To do something like that, you'll have to write a separate Observations class (e.g. `GaussianFixedCovObservations`) and write appropriate `log_likelihoods` and (optionally) `m_step` functions.

Let me know if that answers your question!

Best,
Scott

**Comment by dikshagup** [comment]
Thank you! That answers it, I will go ahead and close the issue.
