### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by pbouss** [lindermanlab/ssm#133]
Hello, 

we were trying to install the ssm-package on a Windows 10 enterprise machine. 

But keep getting this error, when trying to clone:

 C:\Users\...\OneDrive\Documents>git clone https://github.com/lindermanlab/ssm.git
Cloning into 'ssm'...
remote: Enumerating objects: 3077, done.
remote: Counting objects: 100% (302/302), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 3077 (delta 178), reused 204 (delta 109), pack-reused 2775
Receiving objects: 100% (3077/3077), 52.20 MiB | 18.98 MiB/s, done.
Resolving deltas: 100% (2154/2154), done.
error: invalid path 'notebooks/2b Input Driven Observations ("GLM-HMM").ipynb'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Do you have any idea, why this might break?

 I guess it's due to the spaces in the notebook file. 
 
 Thanks for any support and help

**Comment by schlagercollin** [comment]
Hi @pbouss, 

Thank you for bringing this to our attention. The issue was the quotation marks in the filename for a particular notebook: `'notebooks/2b Input Driven Observations ("GLM-HMM").ipynb'`. 

I just pushed an update removing those quotes from the file. You should be able to properly clone on Windows now. I'm going to mark this issue as 'closed', but please feel free to reach out if you run into more issues!

**Comment by pbouss** [comment]
Thanks, it worked nicely now.
